# General
name: Minimal-Block
description: "TIY Las Vegas Python Class<br/> Oct 2015"
url: http://tiy-lv-python-2015-10.github.io/

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: yourusername
twitter: yourusername
github: tiy-lv-python-2015-10
google: +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
